const levels=[
 {name:'ARDA SOYDOĞAN',sprite:'boss-arda.png',giftSprite:'gift-sweater-v2.png',gift:'Yumuşacık bir kazak',note:'Seninle her mevsim içim sıcacık. ♥',power:'KAZAK ZIRHI · Bir sonraki saldırıyı engeller.',x:900},
 {name:'BARIŞ YÜKSEKKAYA',sprite:'boss-baris.png',giftSprite:'gift-record-v2.png',gift:'Birlikte dinlenecek plak',note:'Sen gülünce benim şarkım başlıyor.',power:'RİTİM DALGASI · Pandora atışı artık daha hızlı.',x:1650},
 {name:'BATU CENGİZ',sprite:'boss-batu.png',giftSprite:'gift-surprise-v2.png',gift:'Minik bir sürpriz kutusu',note:'Küçük bir kutuya kocaman sevgimizi sığdırdım.',power:'ŞANS PARÇASI · Her lazer iki hasar verir.',x:2350},
 {name:'MİLAN ÖNDER',sprite:'boss-milan-v2.png',giftSprite:'gift-perfume-v2.png',gift:'Tatlı bir parfüm',note:'Kokusu geçer belki ama sana olan sevgim hiç geçmez.',power:'EKSTRA KALP · Delfin’in can kapasitesi arttı.',x:3050},
 {name:'MİRAÇ FIRAT',sprite:'boss-mirac.png',giftSprite:'gift-photo-v2.png',gift:'Birlikte çekilmiş fotoğraf',note:'En sevdiğim manzara: senin olduğun her yer.',power:'ANLIK KARE · Delfin daha hızlı koşar.',x:3700},
 {name:'OĞUZHAN ÇİFTÇİ',sprite:'boss-oguzhan-v2.png',giftSprite:'gift-chocolate-v2.png',gift:'Kalpli çikolata kutusu',note:'Hayatımdaki en tatlı şey hâlâ sensin.',power:'PARLAK TAŞ · Pandora ateşi üç hasar verir.',x:4400},
 {name:'EFE ŞAN',sprite:'boss-efe.png',giftSprite:'gift-hug-v2.png',gift:'En büyük hediye: sonsuz sarılma',note:'Son boss da bitti. Şimdi hediyeler, sen ve ben.',power:'KALP IŞINI · Pandora yüzüğü tam güçte!',x:5050}
];
const $=s=>document.querySelector(s),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),bgMusic=$('#bgMusic');ctx.imageSmoothingEnabled=false;bgMusic.volume=.45;
const mapWidth=5400,groundY=470,keys={left:false,right:false,fire:false};let running=false,lastTime=0,cameraX=0,collected=0,activeBoss=null,gift=null,shots=[],enemyShots=[],hp=3,maxHearts=3,invincible=0,fireCooldown=0,enemyCooldown=0,checkpoint=80,powers={shield:0,rapid:false,damage:1,speed:1};
const player={x:80,y:370,w:42,h:72,vx:0,vy:0,onGround:false,facing:1};
const platforms=[
 {x:0,y:470,w:650,h:70},{x:760,y:470,w:570,h:70},{x:1420,y:470,w:630,h:70},{x:2160,y:470,w:690,h:70},{x:2940,y:470,w:790,h:70},{x:3840,y:470,w:660,h:70},{x:4600,y:470,w:800,h:70},
 {x:260,y:390,w:150,h:22},{x:470,y:320,w:120,h:22},{x:620,y:400,w:110,h:22},{x:820,y:370,w:150,h:22},{x:1160,y:355,w:130,h:22},
 {x:1300,y:405,w:100,h:22},{x:1480,y:355,w:150,h:22},{x:1700,y:300,w:130,h:22},{x:1900,y:380,w:120,h:22},{x:2050,y:410,w:100,h:22},
 {x:2240,y:370,w:140,h:22},{x:2440,y:315,w:140,h:22},{x:2700,y:385,w:130,h:22},{x:2850,y:415,w:80,h:22},
 {x:3030,y:360,w:150,h:22},{x:3260,y:300,w:120,h:22},{x:3500,y:370,w:150,h:22},{x:3750,y:410,w:80,h:22},
 {x:3980,y:360,w:130,h:22},{x:4200,y:305,w:140,h:22},{x:4450,y:405,w:130,h:22},{x:4660,y:355,w:140,h:22},{x:4780,y:295,w:110,h:22}
];
const loadImage=src=>{const image=new Image();image.src=src;return image};
const delfinFrames=['delfin-idle.png','delfin-run-1.png','delfin-run-2.png','delfin-jump.png'].map(loadImage),bossImages=levels.map(level=>loadImage(level.sprite)),giftImages=levels.map(level=>loadImage(level.giftSprite));
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden')}
function start(){if(bgMusic.paused){bgMusic.currentTime=0;bgMusic.play().catch(()=>toast('Müziği başlatmak için ekrana bir kez daha dokun.'))}collected=0;maxHearts=3;hp=maxHearts;checkpoint=80;powers={shield:0,rapid:false,damage:1,speed:1};Object.assign(player,{x:80,y:360,vx:0,vy:0,onGround:false,facing:1});activeBoss=null;gift=null;shots=[];enemyShots=[];cameraX=0;updateHud();show('#gameScreen');running=true;lastTime=performance.now();requestAnimationFrame(loop);toast('Sağa ilerle, 7 hediyeyi bul!')}
function updateHud(){$('#giftCount').textContent=`${collected} / ${levels.length}`;$('#lifeText').textContent='♥'.repeat(Math.max(0,hp));if(activeBoss)$('#bossMeter').style.width=Math.max(0,activeBoss.hp/activeBoss.maxHp*100)+'%';else $('#bossMeter').style.width='0'}
function spawnBoss(){const spec=levels[collected],maxHp=6+collected*2;activeBoss={index:collected,x:spec.x,y:groundY-82,w:54,h:82,hp:maxHp,maxHp,anchor:spec.x,dir:-1,vx:-1.2,vy:0,onGround:true,jumpCooldown:38,jumpCount:0};enemyCooldown=45;$('#missionText').textContent=spec.name+' karşında!';updateHud();toast(spec.name+' yolu kapattı!')}
function fire(){if(!running||fireCooldown>0)return;fireCooldown=powers.rapid?24:38;shots.push({x:player.x+player.w/2,y:player.y+25,vx:player.facing*15,r:7});}
function jump(){if(running&&player.onGround){player.vy=-15.5;player.onGround=false}}
function hitPlayer(){if(invincible>0)return;if(powers.shield){powers.shield=0;invincible=50;toast('Kazak zırhı saldırıyı engelledi!');return}hp--;invincible=85;updateHud();if(hp<=0){running=false;toast('Delfin düştü, son noktadan devam!');setTimeout(()=>{hp=maxHearts;Object.assign(player,{x:checkpoint,y:350,vx:0,vy:0});if(activeBoss)activeBoss.hp=activeBoss.maxHp;enemyShots=[];shots=[];updateHud();running=true;lastTime=performance.now();requestAnimationFrame(loop)},900)}}
function defeatBoss(){gift={index:activeBoss.index,x:activeBoss.anchor,y:groundY-54,w:46,h:46,bob:0};activeBoss=null;enemyShots=[];$('#missionText').textContent='Hediyenin üzerine git!';updateHud();toast('Hediye düştü — dokunarak aç!')}
function collectGift(){running=false;const d=levels[gift.index],giftIcon=$('#messageGift');checkpoint=d.x+120;$('#messageTitle').textContent=d.gift;$('#messageBody').textContent=d.note;$('#powerupText').textContent=d.power;giftIcon.style.backgroundImage=`url('${d.giftSprite}')`;giftIcon.style.backgroundSize='contain';giftIcon.style.backgroundPosition='center';giftIcon.style.backgroundRepeat='no-repeat';if(gift.index===0)powers.shield=1;if(gift.index===1)powers.rapid=true;if(gift.index===2)powers.damage=2;if(gift.index===3){maxHearts=4;hp=maxHearts}if(gift.index===4)powers.speed=1.35;if(gift.index===5)powers.damage=3;collected++;gift=null;updateHud();show('#messageScreen')}
function continueGame(){if(collected>=levels.length){show('#winScreen');return}show('#gameScreen');$('#missionText').textContent='Sağa ilerle, sonraki parkuru geç.';running=true;lastTime=performance.now();requestAnimationFrame(loop)}
function intersects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function physics(step){player.vx=((keys.right?1:0)-(keys.left?1:0))*6.2*powers.speed;if(player.vx)player.facing=Math.sign(player.vx);const gate=levels[collected]?.x+115||mapWidth-50;player.x=Math.max(0,Math.min(gate,player.x+player.vx*step));const previousBottom=player.y+player.h;player.vy=Math.min(20,player.vy+0.82*step);player.y+=player.vy*step;player.onGround=false;if(player.vy>=0){for(const p of platforms){const newBottom=player.y+player.h;if(player.x+player.w>p.x+5&&player.x<p.x+p.w-5&&previousBottom<=p.y+5&&newBottom>=p.y){player.y=p.y-player.h;player.vy=0;player.onGround=true;break}}}if(player.y>560)hitPlayer(),Object.assign(player,{x:Math.max(20,checkpoint),y:330,vx:0,vy:0});if(collected<levels.length&&!activeBoss&&!gift&&player.x>levels[collected].x-430)spawnBoss();if(keys.fire)fire();if(fireCooldown>0)fireCooldown-=step;if(invincible>0)invincible-=step;cameraX=Math.max(0,Math.min(mapWidth-canvas.width,player.x-canvas.width*.34))}
function moveBoss(step){const boss=activeBoss;if(!boss)return;boss.jumpCooldown-=step;if(boss.onGround){boss.vx=boss.dir*(1.15+boss.index*.06);if(boss.jumpCooldown<=0){boss.jumpCount++;boss.dir=boss.jumpCount%2?Math.sign(player.x-boss.x)||-1:-boss.dir;boss.vx=boss.dir*(4.1+boss.index*.12);boss.vy=-13.8;boss.onGround=false;boss.jumpCooldown=Math.max(52,82-boss.index*3)}}const previousBottom=boss.y+boss.h;boss.x+=boss.vx*step;if(boss.x<boss.anchor-150){boss.x=boss.anchor-150;boss.dir=1;boss.vx=Math.abs(boss.vx)}else if(boss.x>boss.anchor+150){boss.x=boss.anchor+150;boss.dir=-1;boss.vx=-Math.abs(boss.vx)}boss.vy=Math.min(18,boss.vy+.78*step);boss.y+=boss.vy*step;boss.onGround=false;if(boss.vy>=0){for(const p of platforms){const newBottom=boss.y+boss.h;if(boss.x+boss.w>p.x+4&&boss.x<p.x+p.w-4&&previousBottom<=p.y+5&&newBottom>=p.y){boss.y=p.y-boss.h;boss.vy=0;boss.onGround=true;break}}}if(boss.y>560){boss.x=boss.anchor;boss.y=groundY-boss.h;boss.vx=-1.2;boss.vy=0;boss.dir=-1;boss.onGround=true;boss.jumpCooldown=35}}
function combat(step,time){if(activeBoss){moveBoss(step);enemyCooldown-=step;if(enemyCooldown<=0){enemyCooldown=Math.max(40,92-collected*7);const dx=player.x-activeBoss.x,dy=(player.y+30)-(activeBoss.y+35),len=Math.hypot(dx,dy)||1;enemyShots.push({x:activeBoss.x,y:activeBoss.y+30,vx:dx/len*(5.2+collected*.3),vy:dy/len*5.2,r:8})}}
 shots.forEach(s=>s.x+=s.vx*step);enemyShots.forEach(s=>{s.x+=s.vx*step;s.y+=s.vy*step});const target=activeBoss;if(target){let defeated=false;shots=shots.filter(s=>{if(!defeated&&intersects({x:s.x-s.r,y:s.y-s.r,w:s.r*2,h:s.r*2},target)){target.hp-=powers.damage;updateHud();if(target.hp<=0){defeated=true;defeatBoss()}return false}return s.x>cameraX-50&&s.x<cameraX+canvas.width+80})}else shots=shots.filter(s=>s.x>cameraX-50&&s.x<cameraX+canvas.width+80);enemyShots=enemyShots.filter(s=>{if(intersects({x:s.x-s.r,y:s.y-s.r,w:s.r*2,h:s.r*2},player)){hitPlayer();return false}return s.x>cameraX-80&&s.x<cameraX+canvas.width+80});if(gift&&intersects(player,gift))collectGift()}
function drawBackground(){const grad=ctx.createLinearGradient(0,0,0,540);grad.addColorStop(0,'#5c4596');grad.addColorStop(.58,'#ef9f7a');grad.addColorStop(.59,'#29385e');ctx.fillStyle=grad;ctx.fillRect(0,0,960,540);ctx.fillStyle='#443679';for(let i=-1;i<8;i++){const x=((i*190-cameraX*.18)%1700+1700)%1700-160;const h=100+(i%3)*35;ctx.fillRect(x,groundY-h,135,h)}ctx.fillStyle='#ffe08b';ctx.fillRect(0,groundY-3,960,5)}
function drawPlatforms(){for(const p of platforms){const x=p.x-cameraX;if(x>960||x+p.w<0)continue;ctx.fillStyle='#1d2847';ctx.fillRect(x,p.y,p.w,p.h);ctx.fillStyle='#f3d477';ctx.fillRect(x,p.y,p.w,9);ctx.fillStyle='#a87655';for(let q=8;q<p.w;q+=32)ctx.fillRect(x+q,p.y+12,16,5)}}
function drawDelfin(time){let frame=0;if(!player.onGround)frame=3;else if(Math.abs(player.vx)>.1)frame=1+Math.floor(time/125)%2;const image=delfinFrames[frame];if(!image.complete||!image.naturalWidth)return;const dx=player.x-cameraX-8,dy=player.y-14,dw=58,dh=84;ctx.save();if(player.facing<0){ctx.translate(dx+dw,0);ctx.scale(-1,1);ctx.drawImage(image,0,dy,dw,dh)}else ctx.drawImage(image,dx,dy,dw,dh);ctx.restore();ctx.fillStyle='#fff';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText('Delfin',player.x-cameraX+20,player.y-18)}
function drawBoss(time){if(!activeBoss)return;const image=bossImages[activeBoss.index],dx=activeBoss.x-cameraX-10,dy=activeBoss.y-12+(activeBoss.onGround?Math.sin(time/130)*2:0),dw=74,dh=99;if(image.complete&&image.naturalWidth){ctx.save();if(activeBoss.dir<0){ctx.translate(dx+dw,0);ctx.scale(-1,1);ctx.drawImage(image,0,dy,dw,dh)}else ctx.drawImage(image,dx,dy,dw,dh);ctx.restore()}else{ctx.fillStyle='#ff6d9c';ctx.fillRect(dx+18,dy+15,38,68)}ctx.fillStyle='#fff';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText(levels[activeBoss.index].name,activeBoss.x-cameraX+25,activeBoss.y-16)}
function drawGift(time){if(!gift)return;const x=gift.x-cameraX,y=gift.y+Math.sin(time/180)*5,image=giftImages[gift.index];if(image.complete&&image.naturalWidth)ctx.drawImage(image,x,y,50,50);else{ctx.fillStyle='#ffd166';ctx.fillRect(x,y,44,44)}ctx.fillStyle='#fff';ctx.font='bold 12px monospace';ctx.textAlign='center';ctx.fillText('HEDİYE',x+23,y-8)}
function drawShots(){ctx.textAlign='center';ctx.font='bold 25px monospace';for(const s of shots){ctx.fillStyle='#71fff2';ctx.fillText('✦',s.x-cameraX,s.y)}for(const s of enemyShots){ctx.fillStyle='#ff6d9c';ctx.fillText('✹',s.x-cameraX,s.y)}}
function draw(time){drawBackground();drawPlatforms();drawGift(time);drawBoss(time);drawShots();if(invincible<=0||Math.floor(invincible/5)%2===0)drawDelfin(time);ctx.fillStyle='#fff6';ctx.font='11px monospace';ctx.textAlign='left';ctx.fillText(`${Math.floor(player.x/10)} m`,15,24)}
function loop(time){if(!running)return;const step=Math.min(2,(time-lastTime)/16.667||1);lastTime=time;physics(step);combat(step,time);draw(time);canvas.dataset.state=JSON.stringify({running,shots:shots.length,enemyShots:enemyShots.length,x:Math.round(player.x),y:Math.round(player.y),onGround:player.onGround,cameraX:Math.round(cameraX),collected,boss:activeBoss?.index??null,bossX:activeBoss?Math.round(activeBoss.x):null,bossY:activeBoss?Math.round(activeBoss.y):null,bossOnGround:activeBoss?.onGround??null,fireCooldown:Math.ceil(fireCooldown),gift:gift?.index??null});if(running)requestAnimationFrame(loop)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1600)}
function bindHold(button,key){const down=e=>{e.preventDefault();keys[key]=true;button.classList.add('pressed');if(key==='fire')fire();button.setPointerCapture?.(e.pointerId)};const up=()=>{keys[key]=false;button.classList.remove('pressed')};button.addEventListener('pointerdown',down);button.addEventListener('pointerup',up);button.addEventListener('pointercancel',up);button.addEventListener('lostpointercapture',up)}
document.querySelectorAll('[data-hold]').forEach(b=>bindHold(b,b.dataset.hold));bindHold(document.querySelector('[data-action="fire"]'),'fire');document.querySelector('[data-action="jump"]').addEventListener('pointerdown',e=>{e.preventDefault();jump()});document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')keys.left=true;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')keys.right=true;if(e.key==='ArrowUp'||e.key.toLowerCase()==='w'||e.code==='Space'){e.preventDefault();jump()}if(e.key.toLowerCase()==='x'){keys.fire=true;fire()}});document.addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')keys.left=false;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')keys.right=false;if(e.key.toLowerCase()==='x')keys.fire=false});$('#startBtn').addEventListener('click',start);$('#continueBtn').addEventListener('click',continueGame);$('#replayBtn').addEventListener('click',start);window.__gameDebug=()=>({running,shots:shots.length,enemyShots:enemyShots.length,player:{x:Math.round(player.x),y:Math.round(player.y),onGround:player.onGround},cameraX:Math.round(cameraX),collected,boss:activeBoss?.index??null,gift:gift?.index??null});
